### ISSUE TITLE
German 2.8.2 Version Missing

### ISSUE THREAD

**Issue by Hartinger** [pfeerick/lang-firmwares#2]
For some reason, there is no German 2.8.2 firmware version in the zip archive for the x9d+ 2019.

**Comment by pfeerick** [comment]
It's missing because the firmware binary is now too big. The firmware is marginal at the best of times with the x9d radios as they have the smallest amount of flash memory of all the radios supported, and the x9d+2019 DE builds overflowed for 2.8.2. I'll try again with 2.8.3 but I'm not holding my breath.

**Comment by Hartinger** [comment]
Ah, ok. In this case, I will probably go ahead with the English version for my Taranis.

**Comment by pfeerick** [comment]
I can say pretty much for certain 2.9 will be fine... even CZ which is currently turned off for all of the x9d radios should be fine... as we actually have about 17kb of free flash when doing an EN build, so there is plenty of space for DE... One of the benefits of *removing* a feature... conversion from binary storage format... yaml only from 2.9 on onwards. 

However, in building what is going to be 2.8.4 ... ``` region `FLASH' overflowed by 376 bytes``` ... so still close but not quite 😢
