### ISSUE TITLE
Missing Heli tab on x12s-bluetooth-heli-lang-v2.8.4.zip Es

### ISSUE THREAD

**Issue by Fortesque0** [pfeerick/lang-firmwares#4]
Hello,
I have flashed x12s-ES-bluetooth-heli-17692e2.bin using edge tx buddy and doesn't have Heli tab.

 I try too  flashing using boot loader and it start but didn't end. I have to unplug battery and reinstall firmware again using edge buddy.
Please, check this fails.
Regards

**Comment by pfeerick** [comment]
Bootloader update freezing about 80% is probably an intermittent issue - every couple of dozen flashes I experience that also, and it works if you flash it again (after power cycling). 

Heli tab missing is probably because I didn't update the builds scripts after heli was turned off by default... or forgot to add the heli flag to the bluetooth-heli build script  - will fix that soon. Thanks for the report!

**Comment by Fortesque0** [comment]
Hello pfeerick,
 I will be waiting for fixed firmware for start playing with edge tx ;) and my helicopters.
Thanks for your effort!

**Comment by pfeerick** [comment]
Give this one a try :)

https://github.com/pfeerick/lang-firmwares/releases/download/latest/x12s-bluetooth-heli-lang-edb5ecc.zip

**Comment by Fortesque0** [comment]
Hello,
I have install and heli tab it's come back!
Thanks 👍

**Comment by pfeerick** [comment]
Fantastic, Thanks :) 

Resolved by edb5eccedb5577bde962508d3173bba99e1f9dee

**Comment by Fortesque0** [comment]
Hello,
The repositories with new compilations  are not updated.
Regards

**Comment by pfeerick** [comment]
It is present in https://github.com/pfeerick/lang-firmwares/releases/tag/latest, but not in https://github.com/pfeerick/lang-firmwares/releases/tag/v2.8.4 as I've not replaced the bluetooth-heli files in that release _yet_, but will be doing shortly.
